/**
 * Generated artifact templates: the WSL-side start script and the Windows-side
 * tray helper. Both are plain text so they can be written without any Windows
 * process, then a short PowerShell invocation creates the .lnk shortcut.
 */
export const PLUGIN_ID = 'dsh-wsl-tray';
export const WSL_DIR_NAME = 'dsh-wsl-tray';
export const WIN_DIR_REL = '.dsh/dsh-wsl-tray';
export const TRAY_SCRIPT_NAME = 'dsh-tray.ps1';
export const TRAY_VBS_NAME = 'dsh-tray.vbs';
export const ICON_FILE_NAME = 'dsh.ico';
export const START_SCRIPT_NAME = 'start.sh';
export const DEFAULT_SHORTCUT_NAME = 'DeepSeek Harness';
export const DEFAULT_WEB_URL = 'http://127.0.0.1:3080';
/**
 * Build the WSL-side launcher. It starts the same DSH web CLI the running
 * plugin host came from, waits for readiness, and opens the default browser.
 */
export function buildStartScript(params) {
    const logFile = `"$HOME/.dsh/${WSL_DIR_NAME}/start.log"`;
    return `#!/usr/bin/env bash
# Generated by ${PLUGIN_ID}. Do not edit by hand; regenerate from the DSH plugin card.
set -u

URL=${JSON.stringify(params.webUrl)}
LOG_FILE=${logFile}
NODE=${JSON.stringify(params.nodeBin)}
CLI=${JSON.stringify(params.cliBin)}
CWD=${JSON.stringify(params.cwd)}

is_ready() {
  curl -fsS -o /dev/null --max-time 2 "$URL" 2>/dev/null
}

mkdir -p "$(dirname "$LOG_FILE")"

if is_ready; then
  exit 0
fi

cd "$CWD" || {
  echo "Missing DSH directory: $CWD" >&2
  exit 1
}

# Keep DSH in the FOREGROUND of the hidden wsl.exe session: the Windows wsl.exe
# process stays alive as long as DSH runs, which keeps the WSL distro up.
# The tray helper's Windows-side timer opens the browser once the server is up.
exec "$NODE" "$CLI" web --no-open >>"$LOG_FILE" 2>&1
`;
}
export function buildTrayScript(config) {
    const distro = JSON.stringify(config.distro);
    const webUrl = JSON.stringify(config.webUrl);
    const shortcutName = JSON.stringify(config.shortcutName);
    const wslStartScript = JSON.stringify(config.wslStartScript);
    const singleMutex = `Local\\${PLUGIN_ID}-single`;
    return `# Generated by ${PLUGIN_ID}. Do not edit by hand; regenerate from the DSH plugin card.
param(
  [switch]$Regenerate
)

$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName System.Windows.Forms
Add-Type -AssemblyName System.Drawing

$distro = ${distro}
$webUrl = ${webUrl}
$shortcutName = ${shortcutName}
$wslStartScript = ${wslStartScript}
$scriptDir = Split-Path -Parent $PSCommandPath
$iconPath = Join-Path $scriptDir '${ICON_FILE_NAME}'
$vbsPath = Join-Path $scriptDir '${TRAY_VBS_NAME}'

function New-DshShortcut {
  $desktop = [Environment]::GetFolderPath('Desktop')
  $lnkPath = Join-Path $desktop ($shortcutName + '.lnk')
  $shell = New-Object -ComObject WScript.Shell
  $shortcut = $shell.CreateShortcut($lnkPath)
  $shortcut.TargetPath = 'C:\\Windows\\System32\\wscript.exe'
  $shortcut.Arguments = '"' + $vbsPath + '"'
  $shortcut.WorkingDirectory = $scriptDir
  $shortcut.IconLocation = $iconPath + ',0'
  $shortcut.Description = 'DeepSeek Harness (WSL)'
  $shortcut.Save()
}

if ($Regenerate) {
  New-DshShortcut
  Write-Output (Join-Path ([Environment]::GetFolderPath('Desktop')) ($shortcutName + '.lnk'))
  return
}

$launcher = New-Object -ComObject WScript.Shell

function Start-DshWsl {
  $wslCmd = 'wsl.exe -d ' + $distro + ' -- bash -lc "' + $wslStartScript + '"'
  $launcher.Run($wslCmd, 0, $false) | Out-Null
}

function Restart-Dsh {
  $stopCmd = 'wsl.exe -d ' + $distro + ' -- bash -lc "pkill -f ''apps/cli/lib/bin.js web'' || true"'
  $launcher.Run($stopCmd, 0, $true) | Out-Null
  Start-Sleep -Seconds 2
  Start-DshWsl
}

$mutex = New-Object System.Threading.Mutex($false, '${singleMutex}')
try {
  if (-not $mutex.WaitOne(0, $false)) {
    # Second double-click while the tray is already up: open the web page.
    try { Start-Process $webUrl } catch {}
    return
  }
} catch {
  return
}

$tray = New-Object System.Windows.Forms.NotifyIcon
try {
  $tray.Icon = New-Object System.Drawing.Icon($iconPath)
} catch {
  $tray.Icon = [System.Drawing.SystemIcons]::Application
}
$tray.Text = $shortcutName
$tray.Visible = $true
$tray.Add_DoubleClick({ Start-Process $webUrl })

$menu = New-Object System.Windows.Forms.ContextMenuStrip
$openItem = $menu.Items.Add('打开 DeepSeek Harness')
$openItem.Add_Click({ Start-Process $webUrl })
$recreateItem = $menu.Items.Add('重新生成桌面快捷方式')
$recreateItem.Add_Click({ New-DshShortcut })
$restartItem = $menu.Items.Add('重启 DSH 服务')
$restartItem.Add_Click({ Restart-Dsh })
$menu.Items.Add((New-Object System.Windows.Forms.ToolStripSeparator))
$exitItem = $menu.Items.Add('退出')
$exitItem.Add_Click({
  $tray.Visible = $false
  $tray.Dispose()
  [System.Windows.Forms.Application]::Exit()
})
$tray.ContextMenuStrip = $menu

# Start (or reuse) DSH in WSL completely hidden. WScript.Shell.Run with
# window style 0 starts no console window (Start-Process wsl.exe still shows one).
Start-DshWsl

# Windows-side readiness poll: open the default browser once DSH answers.
$readyTimer = New-Object System.Windows.Forms.Timer
$readyTimer.Interval = 2000
$readyTimer.Add_Tick({
  try {
    $response = Invoke-WebRequest -Uri $webUrl -UseBasicParsing -TimeoutSec 2
    if ($response.StatusCode -ge 200 -and $response.StatusCode -lt 300) {
      Start-Process $webUrl
      $readyTimer.Stop()
    }
  } catch {}
})
$readyTimer.Start()

[System.Windows.Forms.Application]::Run()

try {
  $tray.Visible = $false
  $tray.Dispose()
} catch {}
try {
  $mutex.ReleaseMutex()
} catch {}
`;
}
/**
 * Build the Windows-side hidden launcher for the tray helper. The shortcut
 * points at wscript.exe (a GUI-subsystem host, no console) and passes this
 * script; the script derives the PowerShell path from its own location and
 * starts the tray helper with window style 0.
 */
export function buildTrayVbs() {
    return `' Generated by ${PLUGIN_ID}. Do not edit by hand.
Set fso = CreateObject("Scripting.FileSystemObject")
dir = fso.GetParentFolderName(WScript.ScriptFullName)
Set sh = CreateObject("WScript.Shell")
sh.Run "powershell.exe -NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File """ & dir & "\\dsh-tray.ps1""", 0, False
`;
}
