/**
 * Generated artifact templates: the WSL-side start script and the Windows-side
 * tray helper. Both are plain text so they can be written without any Windows
 * process, then a short PowerShell invocation creates the .lnk shortcut.
 */

export const PLUGIN_ID = 'dsh-wsl-tray'
export const WSL_DIR_NAME = 'dsh-wsl-tray'
export const WIN_DIR_REL = '.dsh/dsh-wsl-tray'
export const TRAY_SCRIPT_NAME = 'dsh-tray.ps1'
export const TRAY_VBS_NAME = 'dsh-tray.vbs'
export const ICON_FILE_NAME = 'dsh.ico'
export const START_SCRIPT_NAME = 'start.sh'
export const DEFAULT_SHORTCUT_NAME = 'DeepSeek Harness'
export const DEFAULT_WEB_URL = 'http://127.0.0.1:3080'

/** Parameters baked into both generated scripts. */
export interface LaunchConfig {
  /** WSL distro name passed to `wsl.exe -d`. */
  distro: string
  /** DSH web URL the tray opens and the start script polls. */
  webUrl: string
  /** Shortcut display name (without the .lnk suffix). */
  shortcutName: string
  /** WSL-side path of the generated start script. */
  wslStartScript: string
}

/**
 * Build the WSL-side launcher. It starts the same DSH web CLI the running
 * plugin host came from, waits for readiness, and opens the default browser.
 */
export function buildStartScript(params: {
  nodeBin: string
  sourceCli: string | null
  sourceCwd: string | null
  bakedCli: string | null
  webUrl: string
}): string {
  const logFile = `"$HOME/.dsh/${WSL_DIR_NAME}/start.log"`
  const sourceCli = params.sourceCli === null ? '' : JSON.stringify(params.sourceCli)
  const sourceCwd = params.sourceCwd === null ? '' : JSON.stringify(params.sourceCwd)
  const bakedCli = params.bakedCli === null ? '' : JSON.stringify(params.bakedCli)
  return `#!/usr/bin/env bash
# Generated by ${PLUGIN_ID}. Do not edit by hand; regenerate from the DSH plugin card.
set -u

URL=${JSON.stringify(params.webUrl)}
LOG_FILE=${logFile}
NODE=${JSON.stringify(params.nodeBin)}
SOURCE_CLI=${sourceCli}
SOURCE_CWD=${sourceCwd}
BAKED_CLI=${bakedCli}

is_ready() {
  curl -fsS -o /dev/null --max-time 2 "$URL" 2>/dev/null
}

mkdir -p "$(dirname "$LOG_FILE")"

if is_ready; then
  exit 0
fi

# Launch DSH in the FOREGROUND of the hidden wsl.exe session so WSL keeps the
# distro alive. Try the most reliable launcher first, then fall back to the
# baked-in current CLI, then npx, so source / npm / npx installs all work.
launch_dsh() {
  if command -v dsh >/dev/null 2>&1; then
    exec dsh web --no-open >>"$LOG_FILE" 2>&1
  fi

  if [ -n "$SOURCE_CLI" ] && [ -x "$SOURCE_CLI" ]; then
    if [ -n "$SOURCE_CWD" ] && [ -d "$SOURCE_CWD" ]; then
      cd "$SOURCE_CWD" 2>/dev/null || true
    fi
    exec "$NODE" "$SOURCE_CLI" web --no-open >>"$LOG_FILE" 2>&1
  fi

  if [ -n "$BAKED_CLI" ] && [ -x "$BAKED_CLI" ]; then
    exec "$NODE" "$BAKED_CLI" web --no-open >>"$LOG_FILE" 2>&1
  fi

  if command -v npx >/dev/null 2>&1; then
    exec npx --yes dsh web --no-open >>"$LOG_FILE" 2>&1
  fi

  echo "No usable DSH launcher found. Check $LOG_FILE" >&2
  exit 1
}

launch_dsh
`
}

export function buildTrayScript(config: LaunchConfig): string {
  const distro = JSON.stringify(config.distro)
  const webUrl = JSON.stringify(config.webUrl)
  const shortcutName = JSON.stringify(config.shortcutName)
  const wslStartScript = JSON.stringify(config.wslStartScript)
  const singleMutex = `Local\\${PLUGIN_ID}-single`
  return `# Generated by ${PLUGIN_ID}. Do not edit by hand; regenerate from the DSH plugin card.
param(
  [switch]$Regenerate
)

$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName System.Windows.Forms
Add-Type -AssemblyName System.Drawing

$distro = ${distro}
$webUrl = ${webUrl}
$shortcutName = ${shortcutName}
$wslStartScript = ${wslStartScript}
$scriptDir = Split-Path -Parent $PSCommandPath
$iconPath = Join-Path $scriptDir '${ICON_FILE_NAME}'
$vbsPath = Join-Path $scriptDir '${TRAY_VBS_NAME}'

function New-DshShortcut {
  $desktop = [Environment]::GetFolderPath('Desktop')
  $lnkPath = Join-Path $desktop ($shortcutName + '.lnk')
  $shell = New-Object -ComObject WScript.Shell
  $shortcut = $shell.CreateShortcut($lnkPath)
  $shortcut.TargetPath = 'C:\\Windows\\System32\\wscript.exe'
  $shortcut.Arguments = '"' + $vbsPath + '"'
  $shortcut.WorkingDirectory = $scriptDir
  $shortcut.IconLocation = $iconPath + ',0'
  $shortcut.Description = 'DeepSeek Harness (WSL)'
  $shortcut.Save()
}

if ($Regenerate) {
  New-DshShortcut
  Write-Output (Join-Path ([Environment]::GetFolderPath('Desktop')) ($shortcutName + '.lnk'))
  return
}

$launcher = New-Object -ComObject WScript.Shell

function Start-DshWsl {
  $wslCmd = 'wsl.exe -d ' + $distro + ' -- bash -lc "' + $wslStartScript + '"'
  $launcher.Run($wslCmd, 0, $false) | Out-Null
}

function Stop-Dsh {
  $stopCmd = 'wsl.exe -d ' + $distro + ' -- bash -lc "pkill -f ''apps/cli/lib/bin.js web'' || true"'
  $launcher.Run($stopCmd, 0, $true) | Out-Null
}

function Restart-Dsh {
  Stop-Dsh
  Start-Sleep -Seconds 2
  Start-DshWsl
}

$mutex = New-Object System.Threading.Mutex($false, '${singleMutex}')
try {
  if (-not $mutex.WaitOne(0, $false)) {
    # Second double-click while the tray is already up: open the web page.
    try { Start-Process $webUrl } catch {}
    return
  }
} catch {
  return
}

$tray = New-Object System.Windows.Forms.NotifyIcon
try {
  $tray.Icon = New-Object System.Drawing.Icon($iconPath)
} catch {
  $tray.Icon = [System.Drawing.SystemIcons]::Application
}
$tray.Text = $shortcutName
$tray.Visible = $true
$tray.Add_DoubleClick({ Start-Process $webUrl })

$menu = New-Object System.Windows.Forms.ContextMenuStrip
$openItem = $menu.Items.Add('打开 DeepSeek Harness')
$openItem.Add_Click({ Start-Process $webUrl })
$recreateItem = $menu.Items.Add('重新生成桌面快捷方式')
$recreateItem.Add_Click({ New-DshShortcut })
$restartItem = $menu.Items.Add('重启 DSH 服务')
$restartItem.Add_Click({ Restart-Dsh })
$menu.Items.Add((New-Object System.Windows.Forms.ToolStripSeparator))
$exitItem = $menu.Items.Add('退出')
$exitItem.Add_Click({
  Stop-Dsh
  $tray.Visible = $false
  $tray.Dispose()
  [System.Windows.Forms.Application]::Exit()
})
$tray.ContextMenuStrip = $menu

# Start (or reuse) DSH in WSL completely hidden. WScript.Shell.Run with
# window style 0 starts no console window (Start-Process wsl.exe still shows one).
Start-DshWsl

# Windows-side readiness poll: open the default browser once DSH answers.
$readyTimer = New-Object System.Windows.Forms.Timer
$readyTimer.Interval = 2000
$readyTimer.Add_Tick({
  try {
    $response = Invoke-WebRequest -Uri $webUrl -UseBasicParsing -TimeoutSec 2
    if ($response.StatusCode -ge 200 -and $response.StatusCode -lt 300) {
      Start-Process $webUrl
      $readyTimer.Stop()
    }
  } catch {}
})
$readyTimer.Start()

[System.Windows.Forms.Application]::Run()

try {
  $tray.Visible = $false
  $tray.Dispose()
} catch {}
try {
  $mutex.ReleaseMutex()
} catch {}
`
}


/**
 * Build the Windows-side hidden launcher for the tray helper. The shortcut
 * points at wscript.exe (a GUI-subsystem host, no console) and passes this
 * script; the script derives the PowerShell path from its own location and
 * starts the tray helper with window style 0.
 */
export function buildTrayVbs(): string {
  return `' Generated by ${PLUGIN_ID}. Do not edit by hand.
Set fso = CreateObject("Scripting.FileSystemObject")
dir = fso.GetParentFolderName(WScript.ScriptFullName)
Set sh = CreateObject("WScript.Shell")
sh.Run "powershell.exe -NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File """ & dir & "\\dsh-tray.ps1""", 0, False
`
}
