/**
 * Generated artifact templates: the WSL-side start script and the Windows-side
 * tray helper. Both are plain text so they can be written without any Windows
 * process, then a short PowerShell invocation creates the .lnk shortcut.
 *
 * The tray helper also carries the WATCHDOG, which answers the three design
 * questions of this feature:
 *   1. How DSH liveness is judged: an HTTP probe of the web URL on a timer;
 *      `downThreshold` consecutive failed probes declare DSH down (each probe
 *      records its status code / error text so "refused", "timeout" and
 *      "bad status" stay distinguishable in the log).
 *   2. Restart success is known by the URL answering again within
 *      `restartWaitSec`; each unanswered window counts one failed restart, and
 *      after `maxRestartFailures` consecutive failures the watchdog PAUSES
 *      instead of restarting forever (resume from the tray menu, or it
 *      auto-resumes as soon as DSH answers again).
 *   3. Everything (probes, transitions, restart attempts, pause/resume) is
 *      appended to watchdog.log with timestamps and levels, and a compact
 *      watchdog-status.json is rewritten each tick for the host card.
 */

export const PLUGIN_ID = 'dsh-wsl-tray'
export const WSL_DIR_NAME = 'dsh-wsl-tray'
export const WIN_DIR_REL = '.dsh/dsh-wsl-tray'
export const TRAY_SCRIPT_NAME = 'dsh-tray.ps1'
export const TRAY_VBS_NAME = 'dsh-tray.vbs'
export const ICON_FILE_NAME = 'dsh.ico'
export const START_SCRIPT_NAME = 'start.sh'
export const STOP_SCRIPT_NAME = 'stop.sh'
export const WATCHDOG_LOG_NAME = 'watchdog.log'
export const WATCHDOG_STATUS_NAME = 'watchdog-status.json'
export const DEFAULT_SHORTCUT_NAME = 'DeepSeek Harness'
export const DEFAULT_WEB_URL = 'http://127.0.0.1:3080'

/**
 * Escape a value baked into a PowerShell single-quoted string. JSON escaping
 * is NOT PowerShell escaping: a double-quoted PS string interpolates `$` and
 * treats `"` as a terminator, so baked values must use single quotes with the
 * `''` doubling rule.
 */
function psSingleQuoted(value: string): string {
  return `'${value.replace(/'/g, "''")}'`
}

/** Parameters baked into both generated scripts. */
export interface LaunchConfig {
  /** WSL distro name passed to `wsl.exe -d`. */
  distro: string
  /** DSH web URL the tray opens and the start script polls. */
  webUrl: string
  /** Shortcut display name (without the .lnk suffix). */
  shortcutName: string
  /** WSL-side path of the generated start script. */
  wslStartScript: string
  /** WSL-side path of the generated stop script. */
  wslStopScript: string
}

/**
 * Baked-in watchdog tuning. The tray helper is generated text, so changing
 * these values only takes effect after a regenerate (the plugin's `ensure`
 * compares content and rewrites the tray helper when it differs).
 */
export interface WatchdogConfig {
  /** Master switch. */
  enabled: boolean
  /** Seconds between probes. */
  probeIntervalSec: number
  /** HTTP probe timeout per attempt. */
  probeTimeoutSec: number
  /** Consecutive failed probes that declare DSH down. */
  downThreshold: number
  /** Max seconds a restart may take before it counts as failed. */
  restartWaitSec: number
  /** Give up (pause) after this many consecutive failed restart attempts. */
  maxRestartFailures: number
  /** Cooldown between two failed restart attempts. */
  restartBackoffSec: number
}

export const DEFAULT_WATCHDOG_CONFIG: WatchdogConfig = {
  enabled: true,
  probeIntervalSec: 10,
  probeTimeoutSec: 3,
  downThreshold: 3,
  restartWaitSec: 180,
  maxRestartFailures: 3,
  restartBackoffSec: 60,
}

/**
 * Build the WSL-side launcher. It starts the same DSH web CLI the running
 * plugin host came from, waits for readiness, and opens the default browser.
 */
export function buildStartScript(params: {
  nodeBin: string
  sourceCli: string | null
  sourceCwd: string | null
  bakedCli: string | null
  webUrl: string
}): string {
  const logFile = `"$HOME/.dsh/${WSL_DIR_NAME}/start.log"`
  const sourceCli = params.sourceCli === null ? '' : JSON.stringify(params.sourceCli)
  const sourceCwd = params.sourceCwd === null ? '' : JSON.stringify(params.sourceCwd)
  const bakedCli = params.bakedCli === null ? '' : JSON.stringify(params.bakedCli)
  return `#!/usr/bin/env bash
# Generated by ${PLUGIN_ID}. Do not edit by hand; regenerate from the DSH plugin card.
set -u

URL=${JSON.stringify(params.webUrl)}
LOG_FILE=${logFile}
PID_FILE="$HOME/.dsh/${WSL_DIR_NAME}/dsh.pid"
NODE=${JSON.stringify(params.nodeBin)}
SOURCE_CLI=${sourceCli}
SOURCE_CWD=${sourceCwd}
BAKED_CLI=${bakedCli}

# Liveness probe with a dependency chain: curl, then wget, then bash's own
# /dev/tcp so a minimal distro without downloaders still detects a live DSH.
is_ready() {
  if command -v curl >/dev/null 2>&1; then
    curl -fsS -o /dev/null --max-time 2 "$URL" 2>/dev/null
  elif command -v wget >/dev/null 2>&1; then
    wget -q -T 2 -O /dev/null "$URL" 2>/dev/null
  else
    local host port
    host=\${URL#http://}; host=\${host%%/*}
    port=\${host##*:}; host=\${host%%:*}
    (exec 3<>"/dev/tcp/$host/$port") 2>/dev/null
  fi
}

mkdir -p "$(dirname "$LOG_FILE")"

if is_ready; then
  exit 0
fi

# Launch DSH in the FOREGROUND of the hidden wsl.exe session so WSL keeps the
# distro alive. Try the most reliable launcher first, then fall back to the
# baked-in current CLI, then npx, so source / npm / npx installs all work.
launch_dsh() {
  # exec keeps the shell PID, so this file tracks the final DSH process and
  # stop.sh can stop exactly the instance this script launched.
  echo $$ > "$PID_FILE"
  if command -v dsh >/dev/null 2>&1; then
    exec dsh web --no-open >>"$LOG_FILE" 2>&1
  fi

  if [ -n "$SOURCE_CLI" ] && [ -x "$SOURCE_CLI" ]; then
    if [ -n "$SOURCE_CWD" ] && [ -d "$SOURCE_CWD" ]; then
      cd "$SOURCE_CWD" 2>/dev/null || true
    fi
    exec "$NODE" "$SOURCE_CLI" web --no-open >>"$LOG_FILE" 2>&1
  fi

  if [ -n "$BAKED_CLI" ] && [ -x "$BAKED_CLI" ]; then
    exec "$NODE" "$BAKED_CLI" web --no-open >>"$LOG_FILE" 2>&1
  fi

  if command -v npx >/dev/null 2>&1; then
    exec npx --yes dsh web --no-open >>"$LOG_FILE" 2>&1
  fi

  echo "No usable DSH launcher found. Check $LOG_FILE" >&2
  exit 1
}

launch_dsh
`
}

/**
 * Build the WSL-side stop script. The tray runs it through `wsl.exe`; it
 * stops exactly the instance start.sh launched (PID file, written before
 * exec so it tracks the final DSH process), then falls back to a pkill whose
 * bracketed pattern covers every launcher flavor (source checkout, npm
 * global, npx all end in `bin.js web`) without matching the wsl.exe/bash
 * wrapper that carries the pattern text in its own command line.
 */
export function buildStopScript(): string {
  return `#!/usr/bin/env bash
# Generated by ${PLUGIN_ID}. Do not edit by hand; regenerate from the DSH plugin card.
set -u

PID_FILE="$HOME/.dsh/${WSL_DIR_NAME}/dsh.pid"

if [ -r "$PID_FILE" ]; then
  pid="$(cat "$PID_FILE" 2>/dev/null || true)"
  if [ -n "$pid" ] && kill -0 "$pid" 2>/dev/null; then
    kill "$pid" 2>/dev/null || true
  fi
  rm -f "$PID_FILE"
fi

pkill -f '[b]in\\.js web' 2>/dev/null || true
exit 0
`
}

/**
 * Build the Windows tray helper, including the watchdog state machine.
 *
 * Watchdog phases: `starting` (initial boot grace) → `probing` (steady state)
 * → `restarting` (after a restart trigger, waiting for DSH to answer) →
 * `backoff` (cooldown after a failed restart) or `paused` (auto-give-up after
 * `maxRestartFailures`, or user pause). Any phase returns to `probing` the
 * moment DSH answers again.
 * @param config - launch facts baked into the script.
 * @param watchdog - watchdog tuning baked into the script (defaults when omitted).
 */
export function buildTrayScript(config: LaunchConfig, watchdog: WatchdogConfig = DEFAULT_WATCHDOG_CONFIG): string {
  const distro = psSingleQuoted(config.distro)
  const webUrl = psSingleQuoted(config.webUrl)
  const shortcutName = psSingleQuoted(config.shortcutName)
  const wslStartScript = psSingleQuoted(config.wslStartScript)
  const wslStopScript = psSingleQuoted(config.wslStopScript)
  const singleMutex = `Local\\${PLUGIN_ID}-single`
  const wdEnabled = watchdog.enabled ? '$true' : '$false'
  return `# Generated by ${PLUGIN_ID}. Do not edit by hand; regenerate from the DSH plugin card.
param(
  [switch]$Regenerate
)

$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName System.Windows.Forms
Add-Type -AssemblyName System.Drawing

$distro = ${distro}
$webUrl = ${webUrl}
$shortcutName = ${shortcutName}
$wslStartScript = ${wslStartScript}
$wslStopScript = ${wslStopScript}
$scriptDir = Split-Path -Parent $PSCommandPath
$iconPath = Join-Path $scriptDir '${ICON_FILE_NAME}'
$vbsPath = Join-Path $scriptDir '${TRAY_VBS_NAME}'

# ---- watchdog tuning (baked in; regenerate to change) ----
$watchdogEnabled = ${wdEnabled}
$probeIntervalSec = ${watchdog.probeIntervalSec}
$probeTimeoutSec = ${watchdog.probeTimeoutSec}
$downThreshold = ${watchdog.downThreshold}
$restartWaitSec = ${watchdog.restartWaitSec}
$maxRestartFailures = ${watchdog.maxRestartFailures}
$restartBackoffSec = ${watchdog.restartBackoffSec}
$watchdogLogPath = Join-Path $scriptDir '${WATCHDOG_LOG_NAME}'
$watchdogStatusPath = Join-Path $scriptDir '${WATCHDOG_STATUS_NAME}'
$watchdogLogMaxBytes = 512 * 1024
$watchdogLogKeepLines = 1000

# Mutable watchdog state lives in hashtables so timer/menu handlers mutate
# shared state through $script: references (script scope) reliably.
$script:probe = @{ ok = $false; detail = ''; ms = 0 }
$script:wd = @{
  phase = 'starting'        # starting|probing|restarting|backoff|paused
  probeFailures = 0
  restartFailures = 0
  lastAliveAt = $null
  lastRestartAt = $null
  lastRestartOk = $null     # $null=unknown, $true=ok, $false=failed
  restartDeadline = $null
  backoffDeadline = $null
  autoPaused = $false       # paused because of repeated failures
  userPaused = $false       # paused from the tray menu
  lastThrottleAt = $null
}

function New-DshShortcut {
  $desktop = [Environment]::GetFolderPath('Desktop')
  $lnkPath = Join-Path $desktop ($shortcutName + '.lnk')
  $shell = New-Object -ComObject WScript.Shell
  $shortcut = $shell.CreateShortcut($lnkPath)
  $shortcut.TargetPath = 'C:\\Windows\\System32\\wscript.exe'
  $shortcut.Arguments = '"' + $vbsPath + '"'
  $shortcut.WorkingDirectory = $scriptDir
  $shortcut.IconLocation = $iconPath + ',0'
  $shortcut.Description = 'DeepSeek Harness (WSL)'
  $shortcut.Save()
}

if ($Regenerate) {
  New-DshShortcut
  Write-Output (Join-Path ([Environment]::GetFolderPath('Desktop')) ($shortcutName + '.lnk'))
  return
}

$launcher = New-Object -ComObject WScript.Shell

function Start-DshWsl {
  $wslCmd = 'wsl.exe -d ' + $distro + ' -- bash -lc "' + $wslStartScript + '"'
  $launcher.Run($wslCmd, 0, $false) | Out-Null
}

# Stop/start go through the generated stop.sh so every launcher flavor
# (source checkout, npm global, npx) is covered by one maintained script,
# and so the pkill pattern cannot match the wsl.exe/bash wrapper itself.
function Stop-Dsh {
  $stopCmd = 'wsl.exe -d ' + $distro + ' -- bash ' + $wslStopScript
  $launcher.Run($stopCmd, 0, $true) | Out-Null
}

# Non-blocking stop for the watchdog: the tick handler must never freeze the
# UI thread on a wsl.exe round-trip; restart success is judged by the URL.
function Stop-DshAsync {
  $stopCmd = 'wsl.exe -d ' + $distro + ' -- bash ' + $wslStopScript
  $launcher.Run($stopCmd, 0, $false) | Out-Null
}

function Restart-Dsh {
  Stop-Dsh
  Start-Sleep -Seconds 2
  Start-DshWsl
}

# ---- watchdog core ----

function Write-WatchdogLog {
  param([string]$Level, [string]$Message)
  try {
    $line = '{0} | {1,-5} | {2}' -f (Get-Date -Format 'yyyy-MM-dd HH:mm:ss.fff'), $Level, $Message
    Add-Content -Path $watchdogLogPath -Value $line -Encoding UTF8
    try {
      $len = (Get-Item $watchdogLogPath -ErrorAction SilentlyContinue).Length
      if ($len -gt $watchdogLogMaxBytes) {
        $tail = Get-Content -Path $watchdogLogPath -Tail $watchdogLogKeepLines -Encoding UTF8
        Set-Content -Path $watchdogLogPath -Value $tail -Encoding UTF8
        Add-Content -Path $watchdogLogPath -Value ('{0} | INFO  | watchdog log rotated (kept last {1} lines)' -f (Get-Date -Format 'yyyy-MM-dd HH:mm:ss.fff'), $watchdogLogKeepLines) -Encoding UTF8
      }
    } catch {}
  } catch {}
}

# Avoid log spam during long waits: at most one line per throttled interval.
function Write-WatchdogLogThrottled([string]$Message) {
  $now = Get-Date
  if ($script:wd.lastThrottleAt -eq $null -or ($now - $script:wd.lastThrottleAt).TotalSeconds -ge 30) {
    Write-WatchdogLog 'INFO' $Message
    $script:wd.lastThrottleAt = $now
  }
}

function Test-DshAlive {
  $sw = [System.Diagnostics.Stopwatch]::StartNew()
  $script:probe.detail = ''
  try {
    $resp = Invoke-WebRequest -Uri $webUrl -UseBasicParsing -TimeoutSec $probeTimeoutSec
    $script:probe.ok = ($resp.StatusCode -ge 200 -and $resp.StatusCode -lt 300)
    $script:probe.detail = 'HTTP ' + $resp.StatusCode
  } catch {
    $script:probe.ok = $false
    if ($_.Exception.Response -ne $null) {
      $script:probe.detail = 'HTTP ' + [int]$_.Exception.Response.StatusCode
    } else {
      $script:probe.detail = $_.Exception.Message
    }
  } finally {
    $sw.Stop()
    $script:probe.ms = $sw.ElapsedMilliseconds
  }
}

function Invoke-WatchdogRestart {
  $script:wd.lastRestartAt = Get-Date
  $script:wd.lastRestartOk = $null
  $script:wd.restartDeadline = (Get-Date).AddSeconds($restartWaitSec)
  $attempt = $script:wd.restartFailures + 1
  Write-WatchdogLog 'WARN' ('triggering restart (attempt {0}/{1})' -f $attempt, $maxRestartFailures)
  Stop-DshAsync
  Start-Sleep -Seconds 2
  Start-DshWsl
  $script:wd.phase = 'restarting'
}

function Enter-WatchdogFailure {
  if ($script:wd.restartFailures -ge $maxRestartFailures) {
    $script:wd.phase = 'paused'
    $script:wd.autoPaused = $true
    Write-WatchdogLog 'ERROR' ('gave up after {0} consecutive failed restart attempts; watchdog PAUSED. Resume from the tray menu, or it resumes automatically once DSH answers again.' -f $script:wd.restartFailures)
  } else {
    $script:wd.phase = 'backoff'
    $script:wd.backoffDeadline = (Get-Date).AddSeconds($restartBackoffSec)
    Write-WatchdogLog 'WARN' ('next restart attempt in {0}s (backoff)' -f $restartBackoffSec)
  }
}

function Update-Watchdog {
  if (-not $watchdogEnabled) { return }

  Test-DshAlive
  $alive = $script:probe.ok
  $phase = $script:wd.phase
  $now = Get-Date

  if ($alive) {
    $script:wd.probeFailures = 0
    $script:wd.lastAliveAt = $now
    if ($phase -eq 'starting') {
      $script:wd.phase = 'probing'
      Write-WatchdogLog 'INFO' ('DSH alive: {0} answered ({1}, {2}ms)' -f $webUrl, $script:probe.detail, $script:probe.ms)
    } elseif ($phase -eq 'restarting') {
      $script:wd.lastRestartOk = $true
      $script:wd.restartFailures = 0
      $script:wd.phase = 'probing'
      Write-WatchdogLog 'INFO' ('restart succeeded: {0} answered ({1}, {2}ms); failure count reset' -f $webUrl, $script:probe.detail, $script:probe.ms)
    } elseif ($phase -eq 'backoff') {
      $script:wd.lastRestartOk = $true
      $script:wd.restartFailures = 0
      $script:wd.phase = 'probing'
      Write-WatchdogLog 'INFO' 'DSH recovered during backoff; watchdog back to probing.'
    } elseif ($phase -eq 'paused' -and $script:wd.autoPaused) {
      $script:wd.autoPaused = $false
      $script:wd.restartFailures = 0
      $script:wd.phase = 'probing'
      Write-WatchdogLog 'INFO' 'DSH recovered while watchdog paused; watchdog resumed automatically.'
    }
    # user-paused + alive: stay paused, only timestamps refresh.
    return
  }

  # DSH did not answer this probe.
  if ($phase -eq 'starting') {
    if ($now -gt $script:wd.restartDeadline) {
      $script:wd.restartFailures++
      Write-WatchdogLog 'WARN' ('initial start never became ready within {0}s ({1}); attempt {2}/{3}' -f $restartWaitSec, $script:probe.detail, $script:wd.restartFailures, $maxRestartFailures)
      Enter-WatchdogFailure
    } else {
      Write-WatchdogLogThrottled ('still waiting for the initial DSH start ({0})' -f $script:probe.detail)
    }
    return
  }

  if ($phase -eq 'probing') {
    $script:wd.probeFailures++
    if ($script:wd.probeFailures -eq 1) {
      Write-WatchdogLog 'WARN' ('probe failed ({0}/{1}): {2} ({3})' -f $script:wd.probeFailures, $downThreshold, $webUrl, $script:probe.detail)
    } elseif ($script:wd.probeFailures -eq 2) {
      Write-WatchdogLog 'WARN' ('probe failed ({0}/{1}): {2}' -f $script:wd.probeFailures, $downThreshold, $script:probe.detail)
    }
    if ($script:wd.probeFailures -ge $downThreshold) {
      Write-WatchdogLog 'WARN' ('DSH considered DOWN after {0} consecutive probe failures; triggering restart. Last error: {1}' -f $script:wd.probeFailures, $script:probe.detail)
      Invoke-WatchdogRestart
    }
    return
  }

  if ($phase -eq 'restarting') {
    if ($now -gt $script:wd.restartDeadline) {
      $script:wd.restartFailures++
      $script:wd.lastRestartOk = $false
      Write-WatchdogLog 'WARN' ('restart attempt {0} FAILED: DSH did not answer within {1}s (last error: {2})' -f $script:wd.restartFailures, $restartWaitSec, $script:probe.detail)
      Enter-WatchdogFailure
    } else {
      Write-WatchdogLogThrottled ('restart in progress: still DOWN ({0}); giving it {1}s more' -f $script:probe.detail, [math]::Ceiling(($script:wd.restartDeadline - $now).TotalSeconds))
    }
    return
  }

  if ($phase -eq 'backoff') {
    if ($now -ge $script:wd.backoffDeadline) {
      Write-WatchdogLog 'WARN' ('backoff elapsed; restarting again (attempt {0}/{1})' -f ($script:wd.restartFailures + 1), $maxRestartFailures)
      Invoke-WatchdogRestart
    }
    return
  }

  # paused: watch silently; auto-resume is handled in the alive branch.
}

function Write-WatchdogStatus {
  $now = Get-Date
  $aliveAt = $null
  if ($script:wd.lastAliveAt -ne $null) { $aliveAt = $script:wd.lastAliveAt.ToString('o') }
  $restartAt = $null
  if ($script:wd.lastRestartAt -ne $null) { $restartAt = $script:wd.lastRestartAt.ToString('o') }
  $body = [ordered]@{
    enabled = $watchdogEnabled
    phase = $script:wd.phase
    pausedByUser = $script:wd.userPaused
    autoPaused = $script:wd.autoPaused
    probeFailures = $script:wd.probeFailures
    downThreshold = $downThreshold
    restartFailures = $script:wd.restartFailures
    maxRestartFailures = $maxRestartFailures
    lastProbeDetail = $script:probe.detail
    lastAliveAt = $aliveAt
    lastRestartAt = $restartAt
    lastRestartOk = $script:wd.lastRestartOk
    updatedAt = $now.ToString('o')
  }
  try {
    Set-Content -Path $watchdogStatusPath -Value ($body | ConvertTo-Json -Compress) -Encoding UTF8
  } catch {}
}

function Get-WdPhaseLabel([string]$phase) {
  switch ($phase) {
    'starting'   { return '启动中' }
    'probing'    { return '运行中' }
    'restarting' { return '重启中' }
    'backoff'    { return '冷却中' }
    'paused'     { return '已暂停' }
    default      { return $phase }
  }
}

function Update-WdMenuItems {
  $label = '守护进程: ' + (Get-WdPhaseLabel $script:wd.phase)
  if ($script:wd.autoPaused) { $label += '（连续失败）' }
  if ($script:wd.userPaused) { $label += '（手动）' }
  $script:wdStatusItem.Text = $label
  if ($script:wd.phase -eq 'paused') {
    $script:wdToggleItem.Text = '恢复守护进程'
  } else {
    $script:wdToggleItem.Text = '暂停守护进程'
  }
}

$mutex = New-Object System.Threading.Mutex($false, '${singleMutex}')
try {
  if (-not $mutex.WaitOne(0, $false)) {
    # Second double-click while the tray is already up: open the web page.
    try { Start-Process $webUrl } catch {}
    return
  }
} catch {
  return
}

$tray = New-Object System.Windows.Forms.NotifyIcon
try {
  $tray.Icon = New-Object System.Drawing.Icon($iconPath)
} catch {
  $tray.Icon = [System.Drawing.SystemIcons]::Application
}
$tray.Text = $shortcutName
$tray.Visible = $true
$tray.Add_DoubleClick({ Start-Process $webUrl })

$menu = New-Object System.Windows.Forms.ContextMenuStrip
$script:wdStatusItem = $menu.Items.Add('守护进程: 启动中')
$script:wdStatusItem.Enabled = $false
$script:wdToggleItem = $menu.Items.Add('暂停守护进程')
$script:wdToggleItem.Add_Click({
  if ($script:wd.phase -eq 'paused') {
    $script:wd.userPaused = $false
    $script:wd.autoPaused = $false
    $script:wd.restartFailures = 0
    $script:wd.probeFailures = 0
    $script:wd.phase = 'starting'
    $script:wd.restartDeadline = (Get-Date).AddSeconds($restartWaitSec)
    Write-WatchdogLog 'INFO' 'watchdog resumed from the tray menu'
    Update-WdMenuItems
  } else {
    $script:wd.userPaused = $true
    $script:wd.phase = 'paused'
    Write-WatchdogLog 'INFO' 'watchdog paused from the tray menu (keeps probing, never restarts)'
    Update-WdMenuItems
  }
})
$menu.Items.Add((New-Object System.Windows.Forms.ToolStripSeparator))
$openItem = $menu.Items.Add('打开 DeepSeek Harness')
$openItem.Add_Click({ Start-Process $webUrl })
$recreateItem = $menu.Items.Add('重新生成桌面快捷方式')
$recreateItem.Add_Click({ New-DshShortcut })
$restartItem = $menu.Items.Add('重启 DSH 服务')
$restartItem.Add_Click({
  $script:wd.restartFailures = 0
  $script:wd.autoPaused = $false
  $script:wd.userPaused = $false
  Write-WatchdogLog 'INFO' 'manual restart requested from the tray menu'
  Restart-Dsh
  $script:wd.lastRestartAt = Get-Date
  $script:wd.lastRestartOk = $null
  $script:wd.restartDeadline = (Get-Date).AddSeconds($restartWaitSec)
  $script:wd.phase = 'restarting'
  Update-WdMenuItems
})
$menu.Items.Add((New-Object System.Windows.Forms.ToolStripSeparator))
$exitItem = $menu.Items.Add('退出')
$exitItem.Add_Click({
  Write-WatchdogLog 'INFO' 'tray exiting; watchdog stopped'
  Stop-Dsh
  $tray.Visible = $false
  $tray.Dispose()
  [System.Windows.Forms.Application]::Exit()
})
$tray.ContextMenuStrip = $menu

# Start (or reuse) DSH in WSL completely hidden. WScript.Shell.Run with
# window style 0 starts no console window (Start-Process wsl.exe still shows one).
Start-DshWsl

# Watchdog: start in the 'starting' phase and give DSH a full restartWaitSec
# grace window to answer the very first probe.
$script:wd.phase = 'starting'
$script:wd.restartDeadline = (Get-Date).AddSeconds($restartWaitSec)
Write-WatchdogLog 'INFO' ('watchdog started (probe every {0}s, down after {1} failed probes, max {2} consecutive failed restarts, backoff {3}s, log {4})' -f $probeIntervalSec, $downThreshold, $maxRestartFailures, $restartBackoffSec, $watchdogLogPath)
Write-WatchdogStatus
$script:wdStatusItem.Text = '守护进程: 启动中'
$watchdogTimer = New-Object System.Windows.Forms.Timer
$watchdogTimer.Interval = $probeIntervalSec * 1000
$watchdogTimer.Add_Tick({
  try {
    Update-Watchdog
  } catch {
    Write-WatchdogLog 'ERROR' ('watchdog tick failed: {0}' -f $_.Exception.Message)
  }
  try {
    Write-WatchdogStatus
  } catch {}
  Update-WdMenuItems
})
$watchdogTimer.Start()

# Windows-side readiness poll: open the default browser once DSH answers.
$readyTimer = New-Object System.Windows.Forms.Timer
$readyTimer.Interval = 2000
$readyTimer.Add_Tick({
  try {
    $response = Invoke-WebRequest -Uri $webUrl -UseBasicParsing -TimeoutSec 2
    if ($response.StatusCode -ge 200 -and $response.StatusCode -lt 300) {
      Start-Process $webUrl
      $readyTimer.Stop()
    }
  } catch {}
})
$readyTimer.Start()

[System.Windows.Forms.Application]::Run()

try {
  $readyTimer.Stop()
  $watchdogTimer.Stop()
} catch {}
try {
  $tray.Visible = $false
  $tray.Dispose()
} catch {}
try {
  $mutex.ReleaseMutex()
} catch {}
`
}


/**
 * Build the Windows-side hidden launcher for the tray helper. The shortcut
 * points at wscript.exe (a GUI-subsystem host, no console) and passes this
 * script; the script derives the PowerShell path from its own location and
 * starts the tray helper with window style 0.
 */
export function buildTrayVbs(): string {
  return `' Generated by ${PLUGIN_ID}. Do not edit by hand.
Set fso = CreateObject("Scripting.FileSystemObject")
dir = fso.GetParentFolderName(WScript.ScriptFullName)
Set sh = CreateObject("WScript.Shell")
sh.Run "powershell.exe -NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File """ & dir & "\\dsh-tray.ps1""", 0, False
`
}